name: Run Gradle on PRs
on:
  push:
    tags:
      - 'v[0-9].[0-9].[0-9]'
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build jocke-plugin
        run: ./gradlew buildPlugin

      - name: Release jocke-plugin to GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/distributions/jockes-dependency-plugin-*.zip"
          generateReleaseNotes: true
          artifactContentType: application/zip
          skipIfReleaseExists: true
          artifactErrorsFailBuild: true